// Tests for the engine-free gameplay core.
//
// These mirror the Python and C# suites deliberately. Three implementations of
// the same logic are only useful if they agree, so the RNG tests assert against
// values generated by the Python original: same seed, same world, in any
// language the project ships.

#include <cstdint>
#include <vector>

#include "TinyTest.h"
#include "gamecore/Aabb.h"
#include "gamecore/FixedTimestep.h"
#include "gamecore/Pcg32.h"
#include "gamecore/Sweep.h"
#include "gamecore/TileGrid.h"
#include "gamecore/Vec2.h"

using namespace gamecore;

// ---------------------------------------------------------------- Pcg32 ----

TEST(Pcg32_MatchesReferenceImplementation)
{
    // The canonical PCG32 demo output for seed=42, stream=54. Matching it proves
    // this is really PCG32 and not merely "some generator that looks random".
    const uint32_t Expected[] = {0xA15C02B7u, 0x7B47F409u, 0xBA1D3330u, 0x83D2F293u, 0xBFA4784Bu, 0xCBED606Eu};
    Pcg32 Rng(42, 54);

    for (uint32_t Value : Expected)
    {
        CHECK_EQ(Rng.NextUInt32(), Value);
    }
}

TEST(Pcg32_MatchesThePythonStream)
{
    // Cross-language parity with gamedev/engine/rng.py.
    const uint32_t Expected[] = {
        0x87EDE634u, 0x3433FC18u, 0x810D4AE3u, 0xCD51E088u,
        0x48954F0Eu, 0x4BB5BD5Au, 0x12F4D398u, 0x64EE48C6u,
    };
    Pcg32 Rng(12345, 1);

    for (uint32_t Value : Expected)
    {
        CHECK_EQ(Rng.NextUInt32(), Value);
    }
}

TEST(Pcg32_MatchesThePythonDoubles)
{
    const double Expected[] = {
        0.53097380104600056, 0.50410908313118363,
        0.2835282705406984, 0.074048253851092816,
    };
    Pcg32 Rng(12345, 1);

    for (double Value : Expected)
    {
        CHECK_NEAR(Rng.NextDouble(), Value, 1e-15);
    }
}

TEST(Pcg32_MatchesThePythonBoundedIntegers)
{
    const uint32_t Expected[] = {4, 1, 5, 1, 1, 5, 4, 3, 2, 1, 4, 5};
    Pcg32 Rng(777, 42);

    for (uint32_t Value : Expected)
    {
        CHECK_EQ(Rng.Below(6), Value);
    }
}

TEST(Pcg32_ShufflesIdenticallyToPython)
{
    int Deck[10] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9};
    const int Expected[10] = {1, 3, 8, 7, 0, 4, 9, 6, 5, 2};

    Pcg32 Rng(2026, 7);
    Rng.Shuffle(Deck, 10);

    for (int i = 0; i < 10; ++i)
    {
        CHECK_EQ(Deck[i], Expected[i]);
    }
}

TEST(Pcg32_SeedFromTextMatchesPython)
{
    CHECK_EQ(Pcg32::SeedFromText("cavern"), 0x6712D974B5E1C470ULL);
    CHECK_EQ(Pcg32::SeedFromText(""), 0xCBF29CE484222325ULL);
    CHECK(Pcg32::SeedFromText("cavern") != Pcg32::SeedFromText("caverm"));
}

TEST(Pcg32_SameSeedSameSequence)
{
    Pcg32 A(1234);
    Pcg32 B(1234);

    for (int i = 0; i < 64; ++i)
    {
        CHECK_EQ(A.NextUInt32(), B.NextUInt32());
    }
}

TEST(Pcg32_StreamsAreIndependent)
{
    // Same seed, different stream: distinct sequences. This is what lets terrain
    // and loot share a world seed without interfering.
    Pcg32 Terrain(7, 1);
    Pcg32 Loot(7, 2);
    int Differences = 0;

    for (int i = 0; i < 32; ++i)
    {
        if (Terrain.NextUInt32() != Loot.NextUInt32())
        {
            ++Differences;
        }
    }

    CHECK_EQ(Differences, 32);
}

TEST(Pcg32_BelowIsCloseToUniform)
{
    // Rejection sampling should leave no visible skew across buckets.
    Pcg32 Rng(17);
    int Buckets[6] = {0, 0, 0, 0, 0, 0};
    constexpr int Rolls = 60000;

    for (int i = 0; i < Rolls; ++i)
    {
        Buckets[Rng.Below(6)]++;
    }

    constexpr double ExpectedCount = Rolls / 6.0;
    for (int Count : Buckets)
    {
        CHECK(std::fabs(Count - ExpectedCount) / ExpectedCount < 0.05);
    }
}

TEST(Pcg32_SnapshotReplaysExactly)
{
    Pcg32 Rng(404);
    for (int i = 0; i < 10; ++i)
    {
        Rng.NextUInt32();
    }

    uint64_t State = 0, Increment = 0;
    Rng.Snapshot(State, Increment);

    uint32_t Expected[10];
    for (int i = 0; i < 10; ++i)
    {
        Expected[i] = Rng.NextUInt32();
    }

    Rng.Restore(State, Increment);
    for (int i = 0; i < 10; ++i)
    {
        CHECK_EQ(Rng.NextUInt32(), Expected[i]);
    }
}

// ------------------------------------------------------- Fixed timestep ----

TEST(FixedTimestep_ExactTickCounts)
{
    FixedTimestepAccumulator Accumulator(1.0 / 60.0);
    CHECK_EQ(Accumulator.Feed(1.0 / 60.0), 1);
    CHECK_EQ(Accumulator.Feed(4.0 / 60.0), 4);
    CHECK_EQ(Accumulator.Feed(0.0), 0);
}

TEST(FixedTimestep_SubTickFramesBank)
{
    // A 90 Hz frame is shorter than a 60 Hz tick, so the first cannot produce a
    // tick at all. Three of them are exactly two ticks' worth.
    FixedTimestepAccumulator Accumulator(1.0 / 60.0);
    CHECK_EQ(Accumulator.Feed(1.0 / 90.0), 0);
    CHECK_EQ(Accumulator.Feed(1.0 / 90.0), 1);
    CHECK_EQ(Accumulator.Feed(1.0 / 90.0), 1);
}

TEST(FixedTimestep_HalfRateDisplayIsExact)
{
    // The regression the snap tolerance exists for: without it, thirty frames of
    // 1/30 s sum to 0.9999999999999999 s and floor to 59 ticks instead of 60,
    // surfacing as a periodic one-frame hitch.
    FixedTimestepAccumulator Accumulator(1.0 / 60.0);
    for (int i = 0; i < 600; ++i)
    {
        CHECK_EQ(Accumulator.Feed(1.0 / 30.0), 2);
    }
}

TEST(FixedTimestep_NoDriftOverTenMinutes)
{
    FixedTimestepAccumulator Accumulator(1.0 / 60.0);
    int Total = 0;
    for (int i = 0; i < 36000; ++i)
    {
        Total += Accumulator.Feed(1.0 / 60.0);
    }
    CHECK_EQ(Total, 36000);
}

TEST(FixedTimestep_ClampPreventsTheSpiralOfDeath)
{
    // A ten-second stall must not queue 600 ticks; simulating them would take
    // longer than the stall itself and the game would never recover.
    FixedTimestepAccumulator Accumulator(1.0 / 60.0, 0.25);
    CHECK_EQ(Accumulator.Feed(10.0), 15);
    CHECK_NEAR(Accumulator.GetDroppedTime(), 9.75, 1e-9);
}

TEST(FixedTimestep_AlphaIsTheLeftoverFraction)
{
    FixedTimestepAccumulator Accumulator(1.0 / 60.0);
    Accumulator.Feed(1.5 / 60.0);
    CHECK_NEAR(Accumulator.Alpha(), 0.5, 1e-9);
}

// -------------------------------------------------------------- Vec2 -------

TEST(Vec2_ReflectIsABounce)
{
    // A ball travelling down-right hits a floor whose normal points up.
    const Vec2 Velocity(3.0f, -4.0f);
    const Vec2 Bounced = Velocity.Reflected(Vec2(0.0f, 1.0f));

    CHECK_NEAR(Bounced.X, 3.0f, 1e-5);   // tangential motion preserved
    CHECK_NEAR(Bounced.Y, 4.0f, 1e-5);   // normal component flipped
    CHECK_NEAR(Bounced.Length(), Velocity.Length(), 1e-5);
}

TEST(Vec2_NormalizingZeroIsSafe)
{
    CHECK(Vec2(0.0f, 0.0f).Normalized() == Vec2(0.0f, 0.0f));
}

TEST(Vec2_ClampedIsTerminalVelocity)
{
    CHECK_NEAR(Vec2(30.0f, 40.0f).Clamped(5.0f).Length(), 5.0f, 1e-5);
    CHECK(Vec2(1.0f, 0.0f).Clamped(5.0f) == Vec2(1.0f, 0.0f));
}

// -------------------------------------------------------------- Aabb -------

TEST(Aabb_FlushEdgesDoNotCollideByDefault)
{
    // An entity standing exactly on a floor touches it every frame; if that
    // counted as a collision the resolver would fight it forever.
    const Aabb Floor = Aabb::FromSize(Vec2(0.0f, 0.0f), Vec2(100.0f, 10.0f));
    const Aabb Standing = Aabb::FromSize(Vec2(0.0f, 10.0f), Vec2(10.0f, 10.0f));

    CHECK(!Standing.Overlaps(Floor));
    CHECK(Standing.Overlaps(Floor, true));
}

TEST(Aabb_MinimumTranslationEjectsAlongTheShallowAxis)
{
    const Aabb Mover = Aabb::FromSize(Vec2(0.0f, 8.0f), Vec2(20.0f, 10.0f));
    const Aabb Wall = Aabb::FromSize(Vec2(0.0f, 16.0f), Vec2(20.0f, 10.0f));

    Vec2 Push;
    CHECK(Mover.MinimumTranslation(Wall, Push));
    CHECK_NEAR(Push.X, 0.0f, 1e-5);
    CHECK_NEAR(Push.Y, -2.0f, 1e-5);
}

TEST(Aabb_CircleCornerCaseTheShortcutGetsWrong)
{
    // Expanding the box by the radius is the tempting shortcut and it is wrong
    // outside corners: it makes a square where the reachable region is rounded.
    const Aabb Box = Aabb::FromSize(Vec2(0.0f, 0.0f), Vec2(10.0f, 10.0f));
    const Vec2 Center(-3.0f, -3.0f);

    CHECK(!Box.IntersectsCircle(Center, 4.0f));  // corner is sqrt(18) = 4.24 away
    CHECK(Box.Expanded(4.0f).Contains(Center));  // what the shortcut would say
}

// ------------------------------------------------------------- Sweep -------

TEST(Sweep_DiscreteCollisionMissesAFastMover)
{
    // The bug that motivates continuous detection: the bullet is in front on one
    // tick and behind on the next, never inside, so overlap testing finds nothing
    // and it passes through a solid wall.
    const Aabb Wall = Aabb::FromSize(Vec2(500.0f, 0.0f), Vec2(8.0f, 200.0f));
    const Aabb Bullet = Aabb::FromSize(Vec2(100.0f, 100.0f), Vec2(4.0f, 4.0f));
    const Vec2 Velocity(800.0f, 0.0f);

    CHECK(!Bullet.Overlaps(Wall));
    CHECK(!Bullet.Translated(Velocity).Overlaps(Wall));
    CHECK(Bullet.Right() < Wall.Left());
    CHECK(Bullet.Translated(Velocity).Left() > Wall.Right());
}

TEST(Sweep_CatchesTheFastMover)
{
    const Aabb Wall = Aabb::FromSize(Vec2(500.0f, 0.0f), Vec2(8.0f, 200.0f));
    const Aabb Bullet = Aabb::FromSize(Vec2(100.0f, 100.0f), Vec2(4.0f, 4.0f));

    SweepHit Hit;
    CHECK(SweepAgainst(Bullet, Vec2(800.0f, 0.0f), Wall, Hit));
    CHECK_NEAR(Hit.Time, 396.0 / 800.0, 1e-5);
    CHECK(Hit.Normal == Vec2(-1.0f, 0.0f));
}

TEST(Sweep_ReportsTheCorrectNormalForEachFace)
{
    const Aabb Target = Aabb::FromSize(Vec2(100.0f, 100.0f), Vec2(50.0f, 50.0f));

    struct Case
    {
        Aabb Mover;
        Vec2 Velocity;
        Vec2 Expected;
    };

    const Case Cases[] = {
        {Aabb::FromSize(Vec2(0.0f, 110.0f), Vec2(10.0f, 10.0f)), Vec2(200.0f, 0.0f), Vec2(-1.0f, 0.0f)},
        {Aabb::FromSize(Vec2(200.0f, 110.0f), Vec2(10.0f, 10.0f)), Vec2(-200.0f, 0.0f), Vec2(1.0f, 0.0f)},
        {Aabb::FromSize(Vec2(110.0f, 0.0f), Vec2(10.0f, 10.0f)), Vec2(0.0f, 200.0f), Vec2(0.0f, -1.0f)},
        {Aabb::FromSize(Vec2(110.0f, 200.0f), Vec2(10.0f, 10.0f)), Vec2(0.0f, -200.0f), Vec2(0.0f, 1.0f)},
    };

    for (const Case& C : Cases)
    {
        SweepHit Hit;
        CHECK(SweepAgainst(C.Mover, C.Velocity, Target, Hit));
        CHECK(Hit.Normal == C.Expected);
        CHECK(Hit.Time >= 0.0f && Hit.Time <= 1.0f);
    }
}

TEST(Sweep_ZeroVelocityProducesNoNaN)
{
    const Aabb Target = Aabb::FromSize(Vec2(100.0f, 100.0f), Vec2(50.0f, 50.0f));

    SweepHit Hit;
    CHECK(!SweepAgainst(Aabb::FromSize(Vec2(0.0f, 0.0f), Vec2(10.0f, 10.0f)), Vec2(0.0f, 0.0f), Target, Hit));

    CHECK(SweepAgainst(Aabb::FromSize(Vec2(110.0f, 0.0f), Vec2(10.0f, 10.0f)), Vec2(0.0f, 500.0f), Target, Hit));
    CHECK(!std::isnan(Hit.Time));
}

TEST(Sweep_MatchesBruteForceSampling)
{
    // Analytic geometry is easy to get subtly wrong and hard to eyeball, so check
    // it against a stupid method that is obviously right.
    Pcg32 Rng(1234);
    constexpr int Substeps = 2000;
    int Agreed = 0;
    int Missed = 0;

    for (int Trial = 0; Trial < 400; ++Trial)
    {
        // Every RNG draw goes into a named local before use. C++ leaves the
        // evaluation order of function arguments unspecified, so drawing them
        // inline inside a constructor call would let two compilers assign the
        // same stream to different fields — a test that passes on GCC and fails
        // on MSVC for reasons nothing to do with the code under test.
        const float TargetX = Rng.RangeFloat(-50.0f, 50.0f);
        const float TargetY = Rng.RangeFloat(-50.0f, 50.0f);
        const float TargetW = Rng.RangeFloat(4.0f, 40.0f);
        const float TargetH = Rng.RangeFloat(4.0f, 40.0f);
        const Aabb Target = Aabb::FromSize(Vec2(TargetX, TargetY), Vec2(TargetW, TargetH));

        // Place the mover on a ring around the target and fire roughly at it,
        // with enough jitter that plenty of shots still miss. Sampling both
        // boxes uniformly at random instead makes collisions so rare that the
        // test mostly measures nothing.
        const float Angle = Rng.RangeFloat(0.0f, 6.2831853f);
        const float Distance = Rng.RangeFloat(40.0f, 120.0f);
        const float MoverW = Rng.RangeFloat(2.0f, 20.0f);
        const float MoverH = Rng.RangeFloat(2.0f, 20.0f);
        const Vec2 Offset(std::cos(Angle) * Distance, std::sin(Angle) * Distance);
        const Aabb Mover = Aabb::FromSize(Target.Center() + Offset, Vec2(MoverW, MoverH));

        const float JitterX = Rng.RangeFloat(-45.0f, 45.0f);
        const float JitterY = Rng.RangeFloat(-45.0f, 45.0f);
        const Vec2 Velocity = (Target.Center() - Mover.Center()) * 1.3f + Vec2(JitterX, JitterY);

        if (Mover.Overlaps(Target))
        {
            continue;
        }

        bool bBruteFound = false;
        float BruteTime = 0.0f;
        for (int Step = 0; Step <= Substeps; ++Step)
        {
            const float T = static_cast<float>(Step) / static_cast<float>(Substeps);
            if (Mover.Translated(Velocity * T).Overlaps(Target))
            {
                bBruteFound = true;
                BruteTime = T;
                break;
            }
        }

        if (!bBruteFound)
        {
            ++Missed;
            continue;
        }

        SweepHit Hit;
        CHECK(SweepAgainst(Mover, Velocity, Target, Hit));
        ++Agreed;

        // The analytic answer is exact; sampling can only overshoot, and by at
        // most one substep.
        CHECK(Hit.Time <= BruteTime + 1e-4f);
        CHECK(Hit.Time > BruteTime - (1.0f / Substeps) - 1e-4f);
    }

    // Both arms have to be exercised, or the test proves nothing: all-hits would
    // not check that near misses stay misses, all-misses would not check the
    // maths at all.
    CHECK(Agreed > 50);
    CHECK(Missed > 20);
}

TEST(MoveAndSlide_SlidesAlongAWall)
{
    // Running diagonally into a vertical wall: horizontal motion is cancelled,
    // vertical motion continues. Stopping dead is what makes a game feel like it
    // is made of glue.
    const Aabb Wall = Aabb::FromSize(Vec2(100.0f, -100.0f), Vec2(20.0f, 400.0f));
    SweepHit Hits[4];
    int HitCount = 0;

    const Vec2 Moved = MoveAndSlide(
        Aabb::FromSize(Vec2(50.0f, 0.0f), Vec2(10.0f, 10.0f)),
        Vec2(80.0f, 60.0f), &Wall, 1, Hits, &HitCount);

    CHECK(HitCount > 0);
    CHECK_NEAR(Moved.X, 40.0f, 1e-2);
    CHECK_NEAR(Moved.Y, 60.0f, 1e-2);
}

TEST(MoveAndSlide_SkinIsADistanceNotAFractionOfTheStep)
{
    // The standoff gap must not scale with speed: a slow mover and a fast mover
    // hitting the same wall must stop in the same place.
    const Aabb Wall = Aabb::FromSize(Vec2(100.0f, -100.0f), Vec2(20.0f, 400.0f));
    const Aabb Box = Aabb::FromSize(Vec2(50.0f, 0.0f), Vec2(10.0f, 10.0f));

    const float Slow = MoveAndSlide(Box, Vec2(60.0f, 0.0f), &Wall, 1).X;
    const float Fast = MoveAndSlide(Box, Vec2(6000.0f, 0.0f), &Wall, 1).X;

    CHECK_NEAR(Slow, Fast, 1e-3);
    CHECK_NEAR(Slow, 40.0f, 1e-2);
}

TEST(MoveAndSlide_FastMoverDoesNotTunnel)
{
    const Aabb Wall = Aabb::FromSize(Vec2(500.0f, 0.0f), Vec2(8.0f, 200.0f));
    const Aabb Bullet = Aabb::FromSize(Vec2(100.0f, 100.0f), Vec2(4.0f, 4.0f));

    const Vec2 Moved = MoveAndSlide(Bullet, Vec2(5000.0f, 0.0f), &Wall, 1);
    CHECK(Bullet.Translated(Moved).Right() < Wall.Left() + 1e-2f);
}

TEST(MoveAndSlide_InsideCornerNeedsTwoResolutions)
{
    const Aabb Obstacles[2] = {
        Aabb::FromSize(Vec2(100.0f, 0.0f), Vec2(20.0f, 200.0f)),
        Aabb::FromSize(Vec2(0.0f, 100.0f), Vec2(200.0f, 20.0f)),
    };
    const Aabb Box = Aabb::FromSize(Vec2(50.0f, 50.0f), Vec2(10.0f, 10.0f));

    SweepHit Hits[4];
    int HitCount = 0;
    const Vec2 Moved = MoveAndSlide(Box, Vec2(200.0f, 200.0f), Obstacles, 2, Hits, &HitCount);

    CHECK(HitCount >= 2);
    CHECK(!Box.Translated(Moved).Overlaps(Obstacles[0]));
    CHECK(!Box.Translated(Moved).Overlaps(Obstacles[1]));
}

// ----------------------------------------------------------- TileGrid ------

namespace
{
    const char* const LevelRows[] = {
        "#####",
        "#...#",
        "#.=.#",
        "#...#",
        "#####",
    };
} // namespace

TEST(TileGrid_AsciiIsFlippedSoRowZeroIsTheBottom)
{
    // The single most error-prone part of the port. The first authored line is
    // the top of the screen, but world row 0 must be the ground, or every level
    // loads upside down and every gravity sign is wrong.
    TileGrid Grid(1, 1);
    CHECK(TileGrid::FromAscii(LevelRows, 5, 1.0f, Grid));

    CHECK_EQ(Grid.Get(0, 0), Tile::Solid);
    CHECK_EQ(Grid.Get(2, 0), Tile::Solid);
    CHECK_EQ(Grid.Get(2, 4), Tile::Solid);
    CHECK_EQ(Grid.Get(2, 2), Tile::OneWay);
    CHECK_EQ(Grid.Get(1, 1), Tile::Empty);
}

TEST(TileGrid_OutOfBoundsIsSolidExceptAbove)
{
    TileGrid Grid(1, 1);
    CHECK(TileGrid::FromAscii(LevelRows, 5, 1.0f, Grid));

    CHECK_EQ(Grid.Get(-1, 2), Tile::Solid);
    CHECK_EQ(Grid.Get(99, 2), Tile::Solid);
    CHECK_EQ(Grid.Get(2, -1), Tile::Solid);
    CHECK_EQ(Grid.Get(2, 99), Tile::Empty);
}

TEST(TileGrid_WorldToTileFloorsForNegatives)
{
    // Truncation towards zero maps -0.5 and +0.5 to the same tile, putting an
    // entity standing just left of the origin in the wrong cell.
    TileGrid Grid(10, 10, 16.0f);
    int X = 0, Y = 0;

    Grid.WorldToTile(Vec2(-1.0f, -1.0f), X, Y);
    CHECK_EQ(X, -1);
    CHECK_EQ(Y, -1);

    Grid.WorldToTile(Vec2(-17.0f, -17.0f), X, Y);
    CHECK_EQ(X, -2);
    CHECK_EQ(Y, -2);

    Grid.WorldToTile(Vec2(40.0f, 55.0f), X, Y);
    CHECK_EQ(X, 2);
    CHECK_EQ(Y, 3);
}

TEST(TileGrid_FlushEdgeDoesNotIncludeTheNextTile)
{
    // A box whose right edge sits exactly on a boundary does not overlap the tile
    // beyond it; including that column makes an entity collide with a wall it is
    // merely standing against.
    TileGrid Grid(10, 10, 16.0f);
    int MinX, MinY, MaxX, MaxY;
    Grid.TileRange(Aabb::FromSize(Vec2(0.0f, 0.0f), Vec2(16.0f, 16.0f)), MinX, MinY, MaxX, MaxY);

    CHECK_EQ(MinX, 0);
    CHECK_EQ(MinY, 0);
    CHECK_EQ(MaxX, 0);
    CHECK_EQ(MaxY, 0);
}

TEST(TileGrid_BroadphaseOnlyLooksAtNearbyTiles)
{
    // The rule that makes tile maps viable: cost scales with the size of the
    // entity, not the size of the level.
    TileGrid Big(500, 500, 16.0f);
    for (int X = 0; X < 500; ++X)
    {
        Big.Set(X, 0, Tile::Solid);
    }

    const Aabb Box = Aabb::FromSize(Vec2(100.0f, 0.0f), Vec2(16.0f, 16.0f));
    int MinX, MinY, MaxX, MaxY;
    Big.TileRange(Box, MinX, MinY, MaxX, MaxY);
    const int Inspected = (MaxX - MinX + 1) * (MaxY - MinY + 1);

    CHECK(Inspected <= 4);

    std::vector<Aabb> Boxes;
    Big.BoxesOverlapping(Box, Tile::Solid, Boxes);
    CHECK_EQ(static_cast<int>(Boxes.size()), 2);
}

TEST(TileGrid_RejectsUnknownLegendCharacters)
{
    const char* const Bad[] = {"#?#"};
    TileGrid Grid(1, 1);
    CHECK(!TileGrid::FromAscii(Bad, 1, 1.0f, Grid));
}

TEST(TileGrid_OverlapsAnyDetectsHazards)
{
    const char* const Rows[] = {"...", ".^.", "..."};
    TileGrid Grid(1, 1);
    CHECK(TileGrid::FromAscii(Rows, 3, 1.0f, Grid));

    CHECK(Grid.OverlapsAny(Aabb::FromSize(Vec2(1.0f, 1.0f), Vec2(1.0f, 1.0f)), Tile::Hazard));
    CHECK(!Grid.OverlapsAny(Aabb::FromSize(Vec2(0.0f, 0.0f), Vec2(1.0f, 1.0f)), Tile::Hazard));
}
